import datetime
import this
import codecs

print("Aktuelles Datum und Zeit in eine Variable speichern")
zeit_jetzt = datetime.datetime.now()
print(zeit_jetzt)
print(type(zeit_jetzt))
print()
print("Ausgabe der einzelnen Segmente")
print(datetime.datetime.today().year)
print(datetime.date.today().month)
print(datetime.date.today().day)
print(datetime.datetime.today().hour)
print(datetime.datetime.today().minute)
print(datetime.datetime.today().second)
print()
print("String Manipulation")
print()

zen = codecs.encode(this.s, 'rot13')
print(zen)
zen_original = zen
print()
print("AUFGABE 4")
print()
print(zen.replace('P', ''))
print()
print("AUFGABE 5")
print()
print(zen.split('y'))
print()
print("AUFGABE 6")
print()
print(zen.split('.'))
print()
print("AUFGABE 7")
print()
print(zen.replace('y', 'Y'))
print()
print("AUFGABE 8")
print()
print(zen.find('Complex'))

new_list = zen.split()

print(new_list)

print(new_list.index('Complex'))
print()
print("AUFGABE 9")
print()
print(zen.count('than'))
print()
print("AUFGABE 10")
print()
zen = zen.replace('.', '{}')
print(zen.count('{}'))
print(zen.replace('{}', '5'))
print()
print("AUFGABE 11")
print()
print(len(zen))
print()
print("AUFGABE 12")
print()
print(zen.count(' '))
print()
print("AUFGABE 13")
print()
zen_original = zen_original.replace(' ', '')
zen_original = zen_original.replace('.', '')
print(len(zen_original))
print()
print("AUFGABE 14")
print()
x = 'Kathy Kruck'
print()
print("AUFGABE 15")
print()
x = x.replace(' ', '')
print()
print("AUFGABE 16")
print()
print(x.upper())
print()
print("AUFGABE 17")
print()
print(x + '34')
print()
print("AUFGABE 18")
print()
#x = '000' + x
print(x)
print(x[5])
